groups:
- name: slo.alerts
  rules:
  
  - alert: HighErrorRate
    expr: app:error_rate:rate5m > 0.001
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High error rate"
      description: "Error rate > 0.1% for 2 minutes"